import type { Request, Response, NextFunction, RequestHandler } from "express";

import swagger from "swagger-ui-express";

import { Middleware, MiddlewareClass } from "../../../annotation";
import { _settings, Sapling } from "../../../helper";

// https://github.com/scottie1984/swagger-ui-express/blob/master/README.md

/**
 * Enable the serving of the Swagger endpoint used to serve the OpenAPI spec generated by Sapling.
 *
 * Configure any middleware-specific settings with `Sapling.Extras.swaggerAndOpenApi`
 *
 * You must register `DefaultSwaggerMiddleware.Serve` & `DefaultSwaggerMiddleware.Setup` after `DefaultOpenApiMiddleware`
 *
 * ```ts
 *  const middlewares = [
 *    DefaultOpenApiMiddleware,
 *    DefaultSwaggerMiddleware.Serve,
 *    DefaultSwaggerMiddleware.Setup,
 *  ];
 *  middlewares.map(Sapling.resolve).forEach((r) => app.use(r));
 * ```
 */
@MiddlewareClass()
class Serve {
  private readonly handlers: RequestHandler[] = swagger.serve;

  @Middleware(_settings.doc.swaggerPath)
  handle(request: Request, response: Response, next: NextFunction) {
    return Sapling.chainHandlers(this.handlers, request, response, next);
  }
}

/**
 * Enable the serving of the Swagger endpoint used to serve the OpenAPI spec generated by Sapling.
 *
 * Configure any middleware-specific settings with `Sapling.Extras.swaggerAndOpenApi`
 *
 * You must register `DefaultSwaggerMiddleware.Serve` & `DefaultSwaggerMiddleware.Setup` after `DefaultOpenApiMiddleware`
 *
 * ```ts
 *  const middlewares = [
 *    DefaultOpenApiMiddleware,
 *    DefaultSwaggerMiddleware.Serve,
 *    DefaultSwaggerMiddleware.Setup,
 *  ];
 *  middlewares.map(Sapling.resolve).forEach((r) => app.use(r));
 * ```
 */
@MiddlewareClass()
class Setup {
  private readonly handler: RequestHandler;

  constructor() {
    this.handler = swagger.setup(null, {
      swaggerOptions: { url: _settings.doc.openApiPath },
    });
  }

  @Middleware(_settings.doc.swaggerPath)
  handle(request: Request, response: Response, next: NextFunction) {
    return this.handler(request, response, next);
  }
}

/**
 * Enable the serving of the Swagger endpoint used to serve the OpenAPI spec generated by Sapling.
 *
 * Configure any middleware-specific settings with `Sapling.Extras.swaggerAndOpenApi`
 *
 * You must register `DefaultSwaggerMiddleware.Serve` & `DefaultSwaggerMiddleware.Setup` after `DefaultOpenApiMiddleware`
 *
 * ```ts
 *  const middlewares = [
 *    DefaultOpenApiMiddleware,
 *    DefaultSwaggerMiddleware.Serve,
 *    DefaultSwaggerMiddleware.Setup,
 *  ];
 *  middlewares.map(Sapling.resolve).forEach((r) => app.use(r));
 * ```
 */
export const DefaultSwaggerMiddleware = {
  Serve,
  Setup,
};
