import type { NextFunction, Request, Response } from "express";

import { GET, MiddlewareClass } from "../../../annotation";
import { _settings, ResponseEntity } from "../../../helper";
import { generateOpenApiSpec } from "../../../helper/openapi";

/**
 * Enable the serving of the OpenAPI spec autogenerated by Sapling.
 *
 * Configure any middleware-specific settings with `Sapling.Extras.swaggerAndOpenApi`
 *
 * You must register `DefaultSwaggerMiddleware.Serve` & `DefaultSwaggerMiddleware.Setup` after `DefaultOpenApiMiddleware`
 *
 * ```ts
 *  const middlewares = [
 *    DefaultOpenApiMiddleware,
 *    DefaultSwaggerMiddleware.Serve,
 *    DefaultSwaggerMiddleware.Setup,
 *  ];
 *  middlewares.map(Sapling.resolve).forEach((r) => app.use(r));
 * ```
 */
@MiddlewareClass()
export class DefaultOpenApiMiddleware {
  @GET(_settings.doc.openApiPath)
  handle(_request: Request, _response: Response, _next: NextFunction) {
    return ResponseEntity.ok().body(generateOpenApiSpec());
  }
}
