name: "Setup"
description: "Setup dependencies required to run pipelines"

inputs:
  GPG_PASSPHRASE:
    description: "GPG passphrase if secrets will be used."
    required: false
  GPG_PRIVATE_KEY:
    description: "GPG private key if secrets will be used."
    required: false
  GITHUB_TOKEN:
    description: "GitHub token used to send message"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: tahminator/pipeline/actions/setup@1.0.17
      with:
        GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
